services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_container
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mongo:latest
    hostname: sigma_db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=client
      - MONGO_INITDB_ROOT_USERNAME=flask-access
      - MONGO_INITDB_ROOT_PASSWORD=qwertyuiop
    ports:
      - "27017:27017"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
